github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: false

ports:
  - port: 8800
    onOpen: notify

tasks:
  - name: Install dependencies
    init: |
      brew install replicatedhq/replicated/cli kubectl helm
      curl https://kots.io/install | bash
    command: make helm

vscode:
  extensions:
    - EditorConfig.EditorConfig
    - ms-kubernetes-tools.vscode-kubernetes-tools
