# The installer job is where the magic happens. It generates
# the config, installs Gitpod and then deletes itself when
# it's finished
apiVersion: batch/v1
kind: Job
metadata:
  name: installer
  labels:
    app: gitpod
    component: gitpod-installer
spec:
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      labels:
        app: gitpod
        component: gitpod-installer
    spec:
      serviceAccountName: installer
      restartPolicy: OnFailure
      containers:
        - name: installer
          # Normally, this would be a release but this has additions for Replicated from 2022.01
          image: eu.gcr.io/gitpod-core-dev/build/installer:main.2316
          volumeMounts:
            - mountPath: /config
              name: config
              readOnly: false
          env:
            - name: CONFIG_FILE
              value: /config/config.yaml
          command:
            - /bin/sh
            - -c
          args:
            - |
              set -e

              echo "Gitpod: Generate the base Installer config"
              /app/installer init > "${CONFIG_FILE}"

              echo "Gitpod: Inject the Replicated variables into the config"
              yq e -i '.domain = "{{repl ConfigOption "domain" }}"' "${CONFIG_FILE}"

              echo "Gitpod: Generate the Kubernetes objects and apply"
              /app/installer render -c "${CONFIG_FILE}" --namespace {{repl Namespace }} | kubectl apply -f -

              echo "Gitpod: Delete Installer resources - prevents the elevated privileges being used and abused"
              kubectl delete serviceaccount installer -n {{repl Namespace }}

              echo "Gitpod: Installer job finished - goodbye"
      volumes:
        - name: config
          emptyDir: {}
