# This is the service account that the Installer uses. This
# is deleted when the job exits successfully
apiVersion: v1
kind: ServiceAccount
metadata:
  name: installer
  labels:
    app: gitpod
    component: gitpod-installer
