apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: gitpod
spec:
  groups:
    - name: general
      title: General settings
      description: General settings for your Gitpod instance
      items:
        - name: domain
          title: What is your domain name?
          help_text: This will be the URL that you use to access your Gitpod instance. This should be in the format "gitpod.domain.com".
          type: text
          required: true

    - name: container_registry
      title: Container registry
      description: Gitpod requires a container registry to store container images. This can either be an in-cluster or external container registry.
      items:
        - name: reg_incluster
          title: Use in-cluster container registry
          type: bool
          default: "1"
          help_text: You may either use an in-cluster container registry or configure your own external container registry for better performance. This container registry must be accessible from your Kubernetes cluster.
          recommended: false

        - name: reg_url
          title: Container registry URL
          type: text
          when: '{{repl ConfigOptionEquals "reg_incluster" "0" }}'
          required: true
          help_text: The container registry URL. This will usually be the fully qualified domain of your registry.

        - name: reg_server
          title: Container registry server
          type: text
          when: '{{repl ConfigOptionEquals "reg_incluster" "0" }}'
          help_text: The container registry server. This is used when [generating your credentials](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-secret-by-providing-credentials-on-the-command-line). Depending upon your provider, this may or may not be the same as the registry URL. If not specified, the URL will be used.

        - name: reg_username
          title: Container registry username
          type: text
          when: '{{repl ConfigOptionEquals "reg_incluster" "0" }}'
          required: true
          help_text: The username for your container registry.

        - name: reg_password
          title: Container registry password
          type: password
          when: '{{repl ConfigOptionEquals "reg_incluster" "0" }}'
          required: true
          help_text: The password for your container registry.

        - name: reg_s3storage
          title: Use S3 storage for your container registry
          type: bool
          default: "0"
          when: '{{repl ConfigOptionEquals "reg_incluster" "0" }}'
          help_text: If using AWS as your container registry, you must configure an S3 storage backend.

        - name: reg_bucketname
          title: S3 bucket name
          type: text
          when: '{{repl and (ConfigOptionEquals "reg_incluster" "0") (ConfigOptionEquals "reg_s3storage" "1") }}'
          required: true
          help_text: The name of the bucket to act as your S3 storage backend.

        - name: reg_accesskey
          title: S3 access key
          type: text
          when: '{{repl and (ConfigOptionEquals "reg_incluster" "0") (ConfigOptionEquals "reg_s3storage" "1") }}'
          required: true
          help_text: The access key to use for authentication of your S3 storage backend.

        - name: reg_secretkey
          title: S3 secret key
          type: password
          when: '{{repl and (ConfigOptionEquals "reg_incluster" "0") (ConfigOptionEquals "reg_s3storage" "1") }}'
          required: true
          help_text: The secret key to use for authentication of your S3 storage backend.

    - name: database
      title: Database
      description: Gitpod requires an instance of MySQL 5.7 for data storage. This can either be an in-cluster or external database.
      items:
        - name: db_incluster
          title: Use MySQL in-cluster
          type: bool
          default: "1"
          help_text: You may either use an in-cluster database or configure your own external database for better performance. This database must be accessible from your Kubernetes cluster.
          recommended: false

        - name: db_cloudsql_enabled
          title: Use Google Cloud SQL Proxy
          when: '{{repl (ConfigOptionEquals "db_incluster" "0") }}'
          type: bool
          default: "0"
          help_text: "Gitpod natively supports [Google Cloud SQL Proxy](https://cloud.google.com/sql/docs/mysql/sql-proxy) to secure the connection. If this is not used, you will need to ensure that the database route is secured. **NB.** this only works with GCP provided databases."

        - name: db_cloudsql_instance
          title: CloudSQL connection name
          type: text
          when: '{{repl and (ConfigOptionEquals "db_incluster" "0") (ConfigOptionEquals "db_cloudsql_enabled" "1") }}'
          required: true
          help_text: The CloudSQL connection name. This will be in the format "<project>:<region>:<instance-name>".

        - name: db_encryption_keys
          title: Encryption keys
          type: text
          hidden: true
          required: true
          value: '[{"name":"general","version":1,"primary":true,"material":"4uGh1q8y2DYryJwrVMHs0kWXJlqvHWWt/KJuNi04edI="}]'

        - name: db_host
          title: Host
          type: text
          when: '{{repl and (ConfigOptionEquals "db_incluster" "0") (ConfigOptionEquals "db_cloudsql_enabled" "0") }}'
          required: true
          help_text: The host of your database. This can be an IP address or a URL.

        - name: db_username
          title: Username
          when: '{{repl (ConfigOptionEquals "db_incluster" "0") }}'
          type: text
          value: gitpod
          required: true
          help_text: The username for your database.

        - name: db_password
          title: Password
          when: '{{repl (ConfigOptionEquals "db_incluster" "0") }}'
          type: password
          required: true
          help_text: The password for your database.

        - name: db_port
          title: Port
          type: text
          when: '{{repl and (ConfigOptionEquals "db_incluster" "0") (ConfigOptionEquals "db_cloudsql_enabled" "0") }}'
          value: "3306"
          required: true
          help_text: The port for your database.

        - name: db_gcp_credentials
          title: GCP service account key
          when: '{{repl and (ConfigOptionEquals "db_incluster" "0") (ConfigOptionEquals "db_cloudsql_enabled" "1") }}'
          type: file
          required: true
          help_text: Download a [service account key](https://cloud.google.com/iam/docs/creating-managing-service-account-keys) with the `roles/cloudsql.client` role attached.
